"""Role S-02 analyzer tests: forward -> file -> analyze round-trips (18 G5).

The G5 fixtures are *synthetic*: short records generated by a forward run
(photodiode detector) and saved to the loader formats (doc 20 §5); the golden
references are the metrics of the source run's own standard-DSP result, so the
analyzer is checked against the same tract that produced the record (17 §7).
Tolerances follow doc 11 §7 (DSP recovery; the only analyzer-specific delta is
the dc-level estimate: the record uses the sample mean instead of the true
pedestal). Real E-0/E-3 records will later land additively in ``tests/data/``
per the 18 §5/§6 gates (rule 18 §5(g): golden refer to the base formulas).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from pydantic import ValidationError

from optivibe.analysis.instrument import (
    AnalyzeSpec,
    CalibrationSpec,
    analyze_record,
    load_analyze_spec,
)
from optivibe.cli.main import main as cli_main
from optivibe.core.config.loader import load_constants, load_variant
from optivibe.core.config.models import (
    Constants,
    ScenarioConfig,
    SineSpec,
    StageSelection,
    VariantConfig,
)
from optivibe.dsp.calibration import dynamic_sensitivity, target_sensitivity
from optivibe.dsp.nea import nea_from_psd
from optivibe.mechanics.cantilever import CantileverModel
from optivibe.pipeline.orchestrator import Pipeline, RunArtifacts

F0 = 200.0
FS = 5000.0
TS = "2026-07-04T00:00:00"


@pytest.fixture(scope="module")
def constants(config_dir: Path) -> Constants:
    return load_constants(config_dir / "constants.yaml")


@pytest.fixture(scope="module")
def variant_b(config_dir: Path) -> VariantConfig:
    return load_variant("B", config_dir)


@pytest.fixture(scope="module")
def forward_b(variant_b: VariantConfig) -> RunArtifacts:
    """One forward + inverse run of variant B (photodiode + standard DSP)."""
    excitation = SineSpec(
        kind="sine", axis="x", fs_hz=FS, duration_s=1.0, frequency_hz=F0, amplitude_g=1.0
    )
    scenario = ScenarioConfig(
        name="s02-fixture",
        variant="B",
        excitation=excitation,
        stages=StageSelection(detector="photodiode", dsp="standard"),
        seed=7,
    )
    return Pipeline(scenario, variant_b).run()


def _write_record_csv(path: Path, artifacts: RunArtifacts, *, reference: bool = True) -> None:
    """Save the forward photocurrent (and reference accel) as a CSV record (G5)."""
    det = artifacts.forward.detector
    t = np.arange(det.n_samples) / det.fs
    cols = [t, det.samples]
    header = "time_s,i_pd_a"
    if reference:
        cols.append(artifacts.forward.excitation.a_x)
        header += ",a_ref_m_s2"
    np.savetxt(path, np.column_stack(cols), delimiter=",", header=header, comments="", fmt="%.17e")


def _spec(path: Path, variant: str, calibration: dict[str, object] | None) -> AnalyzeSpec:
    record: dict[str, object] = {
        "format": "csv",
        "path": str(path),
        "units": "A",
        "column": "i_pd_a",
        "time_column": "time_s",
        "timestamp": TS,
        "reference": {"channel": "a_ref_m_s2", "units": "m/s^2"},
    }
    return AnalyzeSpec.model_validate(
        {
            "kind": "analyze",
            "name": "t",
            "variant": variant,
            "record": record,
            "calibration": calibration,
        }
    )


# --------------------------------------------------------------------------- #
# Round-trip golden: forward -> file -> analyze (18 G5)
# --------------------------------------------------------------------------- #
@pytest.mark.golden
def test_analyze_roundtrip_matches_forward_metrics(tmp_path: Path, forward_b: RunArtifacts) -> None:
    """The analyzer reproduces the source run's own standard-DSP metrics.

    Same samples, same chain (17 §7); the only difference is the dc-level
    estimate (sample mean vs true pedestal), a << 0.1 % effect at this SNR.
    """
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    analysis = analyze_record(_spec(path, "B", {"source": "model"}))
    assert analysis.result is not None
    source = forward_b.result
    # Dominant lines coincide (17 §1 "spectral dominants", same estimator).
    assert analysis.dominant_freqs_hz[0] == pytest.approx(F0, abs=0.5)
    assert analysis.result.dominant_freqs_hz[0] == pytest.approx(
        source.dominant_freqs_hz[0], abs=1e-6
    )
    # Calibrated RMS metrics within the dc-estimate delta (11 §7 DSP recovery).
    for key in ("a", "v", "x"):
        assert analysis.result.rms[key] == pytest.approx(source.rms[key], rel=1e-3)
    # The ISO assessment is the same tract: identical zone and class.
    assert analysis.result.iso is not None and source.iso is not None
    assert analysis.result.iso["zone"] == source.iso["zone"]
    assert analysis.result.iso["machine_class"] == source.iso["machine_class"]
    # THD proxy (2f/1f) is tiny for the linear-regime tone.
    assert analysis.second_harmonic_ratio is not None
    assert analysis.second_harmonic_ratio < 0.01


@pytest.mark.golden
def test_measured_scalar_equal_to_model_is_bit_identical(
    tmp_path: Path, forward_b: RunArtifacts, variant_b: VariantConfig, constants: Constants
) -> None:
    """'measured' with the model scalar reproduces the 'model' source bit-for-bit.

    Pins the injection mechanism (StandardDsp sensitivity_model, SW-52): the
    measured path runs the *same* chain, only the scalar source differs.
    """
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    s_model = target_sensitivity(variant_b, constants)
    a_model = analyze_record(_spec(path, "B", {"source": "model"}))
    a_meas = analyze_record(
        _spec(path, "B", {"source": "measured", "s_target_a_per_m_s2": s_model})
    )
    assert a_model.result is not None and a_meas.result is not None
    np.testing.assert_array_equal(a_meas.result.a, a_model.result.a)
    np.testing.assert_array_equal(a_meas.result.v, a_model.result.v)
    assert a_meas.result.rms == a_model.result.rms


@pytest.mark.golden
def test_bench_source_estimates_the_model_sensitivity(
    tmp_path: Path, forward_b: RunArtifacts, variant_b: VariantConfig, constants: Constants
) -> None:
    """The bench estimate from the paired reference matches |s_target D(f0)|.

    For a single tone the RMS-ratio estimator returns the through sensitivity
    at the tone (doc 05 §2b); at f0 << f1 the plateau scalar within noise.
    """
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    analysis = analyze_record(_spec(path, "B", {"source": "bench"}))
    assert analysis.s_target_bench_estimate is not None
    s_f0 = float(np.abs(dynamic_sensitivity(variant_b, np.asarray([F0]), constants))[0])
    assert abs(analysis.s_target_bench_estimate) == pytest.approx(s_f0, rel=0.02)
    # The sign carries the slope inversion (doc 05 §2): negative for v1.
    assert analysis.s_target_bench_estimate < 0.0
    # And the calibrated recovery lands on the applied excitation.
    assert analysis.result is not None
    applied_rms = float(np.sqrt(np.mean(forward_b.forward.excitation.a_x**2)))
    assert analysis.result.rms["a"] == pytest.approx(applied_rms, rel=0.02)


@pytest.mark.golden
def test_nea_referral_identity(
    tmp_path: Path, forward_b: RunArtifacts, variant_b: VariantConfig, constants: Constants
) -> None:
    """NEA(f) equals sqrt(S_I(f)) / |s_target D(f)| bin-for-bin (doc 05 §7).

    Pins the measured-PSD referral convention: the dynamic roll-up D(f) from
    the (shape-agnostic) cantilever divides the plateau scalar.
    """
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    analysis = analyze_record(_spec(path, "B", {"source": "model"}))
    assert analysis.nea_density is not None and analysis.nea_freq_hz is not None
    s_qs = target_sensitivity(variant_b, constants)
    cantilever = CantileverModel.from_config(constants, variant_b)
    s_f = np.abs(s_qs * cantilever.dynamic_factor(analysis.psd.freq))
    expected = np.sqrt(np.maximum(analysis.psd.values, 0.0)) / s_f
    np.testing.assert_allclose(analysis.nea_density, expected, rtol=1e-12)
    assert analysis.nea_full_band_m_s2 is not None
    assert analysis.nea_full_band_m_s2 > 0.0


# --------------------------------------------------------------------------- #
# Boundary G9 and graceful degradation (20 §5)
# --------------------------------------------------------------------------- #
def test_model_source_on_sphere_is_loud_g9(tmp_path: Path, forward_b: RunArtifacts) -> None:
    """The model calibration refuses non-cylinder shapes with a G9 pointer."""
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    with pytest.raises(ValueError, match="cylinder-only"):
        analyze_record(_spec(path, "proto_poc", {"source": "model"}))


def test_sphere_with_measured_scalar_works(tmp_path: Path, forward_b: RunArtifacts) -> None:
    """A measured scalar calibrates any shape (proto_poc, sphere) -- G9 kept."""
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    analysis = analyze_record(
        _spec(path, "proto_poc", {"source": "measured", "s_target_a_per_m_s2": -2.0e-7})
    )
    assert analysis.result is not None
    assert analysis.dominant_freqs_hz[0] == pytest.approx(F0, abs=0.5)
    assert analysis.calibration is not None
    assert analysis.calibration["source"] == "measured"


def test_no_calibration_degrades_gracefully(tmp_path: Path, forward_b: RunArtifacts) -> None:
    """Without calibration the scale-free metrics are still produced (20 §5)."""
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b, reference=False)
    spec = _spec(path, "proto_poc", None)
    record = spec.record.model_copy(update={"reference": None})
    analysis = analyze_record(spec.model_copy(update={"record": record}))
    assert analysis.result is None
    assert analysis.nea_density is None
    assert analysis.calibration is None
    assert analysis.dominant_freqs_hz[0] == pytest.approx(F0, abs=0.5)
    assert analysis.second_harmonic_ratio is not None
    assert analysis.i_ac_rms_a > 0.0
    assert analysis.psd.kind == "psd"


def test_bench_source_without_reference_is_loud(tmp_path: Path, forward_b: RunArtifacts) -> None:
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b, reference=False)
    spec = _spec(path, "B", {"source": "bench"})
    record = spec.record.model_copy(update={"reference": None})
    with pytest.raises(ValueError, match="reference channel"):
        analyze_record(spec.model_copy(update={"record": record}))


def test_calibration_spec_scalar_rules() -> None:
    """'measured' requires the scalar; other sources must not carry it."""
    with pytest.raises(ValidationError, match="s_target"):
        CalibrationSpec(source="measured")
    with pytest.raises(ValidationError, match="exclusive"):
        CalibrationSpec(source="model", s_target_a_per_m_s2=-1.0e-7)


def test_nea_from_psd_guards() -> None:
    """The referral rejects non-PSD spectra and degenerate sensitivities."""
    from optivibe.core.types import Spectrum

    freq = np.linspace(0.0, 100.0, 11)
    amp = Spectrum(freq=freq, values=np.ones_like(freq), kind="amplitude")
    with pytest.raises(ValueError, match="PSD"):
        nea_from_psd(amp, 1.0)
    psd = Spectrum(freq=freq, values=np.ones_like(freq), kind="psd")
    with pytest.raises(ValueError, match="positive"):
        nea_from_psd(psd, 0.0)
    with pytest.raises(ValueError, match="grid"):
        nea_from_psd(psd, np.ones(3))


# --------------------------------------------------------------------------- #
# HDF5 round-trip (bit-exact float64 container) and the CLI
# --------------------------------------------------------------------------- #
def test_analyze_hdf5_roundtrip(tmp_path: Path, forward_b: RunArtifacts) -> None:
    h5py = pytest.importorskip("h5py")
    det = forward_b.forward.detector
    path = tmp_path / "rec.h5"
    with h5py.File(path, "w") as handle:
        ds = handle.create_dataset("i_pd", data=det.samples)
        ds.attrs["fs"] = det.fs
    spec = AnalyzeSpec.model_validate(
        {
            "kind": "analyze",
            "name": "t",
            "variant": "B",
            "record": {
                "format": "hdf5",
                "path": str(path),
                "dataset": "i_pd",
                "units": "A",
                "fs_attr": "fs",
                "timestamp": TS,
            },
            "calibration": {"source": "model"},
        }
    )
    analysis = analyze_record(spec)
    assert analysis.result is not None
    assert analysis.dominant_freqs_hz[0] == pytest.approx(F0, abs=0.5)


def test_load_analyze_spec_rejects_wrong_kind(tmp_path: Path) -> None:
    path = tmp_path / "spec.yaml"
    path.write_text("kind: sweep\nname: x\n")
    with pytest.raises(ValueError, match="analyze"):
        load_analyze_spec(path)


def test_cli_analyze_acceptance(capsys: pytest.CaptureFixture[str], repo_root: Path) -> None:
    """The shipped example record analyzes to the 120 Hz dominant (CLI, S-02)."""
    code = cli_main(
        [
            "analyze",
            str(repo_root / "examples" / "analyze_record.yaml"),
            "--config-dir",
            str(repo_root / "configs"),
        ]
    )
    out = capsys.readouterr().out
    assert code == 0
    assert "dominant : 120.000" in out
    assert "calibration : bench" in out
    assert "ISO" in out


def test_cli_analyze_record_override_and_errors(
    tmp_path: Path, forward_b: RunArtifacts, repo_root: Path
) -> None:
    """--record repoints the descriptor; a missing spec exits with code 2."""
    path = tmp_path / "rec.csv"
    _write_record_csv(path, forward_b)
    spec_path = tmp_path / "spec.yaml"
    spec_path.write_text(
        "\n".join(
            [
                "kind: analyze",
                "name: t",
                "variant: B",
                "record:",
                "  format: csv",
                "  path: does-not-exist.csv",
                "  units: A",
                "  column: i_pd_a",
                "  time_column: time_s",
                f'  timestamp: "{TS}"',
                "calibration:",
                "  source: model",
            ]
        )
    )
    code = cli_main(
        [
            "analyze",
            str(spec_path),
            "--record",
            str(path),
            "--config-dir",
            str(repo_root / "configs"),
        ]
    )
    assert code == 0
    assert cli_main(["analyze", str(tmp_path / "missing.yaml")]) == 2
